title: Jeremy Gale
description: "Dad. iOS Developer. SwiftUI enthusiast. Hockey fan. Foodie. Human being. "
google_analytics: UA-74286808-1
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
